# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Description of what the lane does"
  
  lane :custom_lane do
    
    # Checkout realease branch
    # ensure_git_status_clean

    # Clear Data
    clear_derived_data
    xcclean(
      scheme: "GBShop"
    )

    # Update a dependencies
    # cocoapods(
    #   use_bundle_exec: false
    # )

    # Run tests
    run_tests

    # Make screenshots
    # capture_ios_screenshots

  end

  lane :project do
    
    increment_build_number
    set_info_plist_value(
      path: "./GBShop/Environments/Info.plist", 
      key: "CFBundleShortVersionString", 
      value: "2.0"
    )

    gym(
      scheme: "GBShop",
      configuration: "Debug",
      # export_method: "development",
      include_symbols: true,
      include_bitcode: true,
      silent: false
    )

  end

end
